/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardExperimentsIndexRouteImport } from './routes/_dashboard/dashboard/experiments/index'
import { Route as DashboardDashboardExperimentsExperimentIdRouteRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/route'
import { Route as DashboardDashboardExperimentsExperimentIdIndexRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/index'
import { Route as DashboardDashboardExperimentsExperimentIdSettingsRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardExperimentsIndexRoute =
  DashboardDashboardExperimentsIndexRouteImport.update({
    id: '/dashboard/experiments/',
    path: '/dashboard/experiments/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdRouteRoute =
  DashboardDashboardExperimentsExperimentIdRouteRouteImport.update({
    id: '/dashboard/experiments/$experimentId',
    path: '/dashboard/experiments/$experimentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdIndexRoute =
  DashboardDashboardExperimentsExperimentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardExperimentsExperimentIdRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdSettingsRoute =
  DashboardDashboardExperimentsExperimentIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardDashboardExperimentsExperimentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/experiments/$experimentId': typeof DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren
  '/dashboard/experiments/': typeof DashboardDashboardExperimentsIndexRoute
  '/dashboard/experiments/$experimentId/settings': typeof DashboardDashboardExperimentsExperimentIdSettingsRoute
  '/dashboard/experiments/$experimentId/': typeof DashboardDashboardExperimentsExperimentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/experiments': typeof DashboardDashboardExperimentsIndexRoute
  '/dashboard/experiments/$experimentId/settings': typeof DashboardDashboardExperimentsExperimentIdSettingsRoute
  '/dashboard/experiments/$experimentId': typeof DashboardDashboardExperimentsExperimentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/experiments/$experimentId': typeof DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren
  '/_dashboard/dashboard/experiments/': typeof DashboardDashboardExperimentsIndexRoute
  '/_dashboard/dashboard/experiments/$experimentId/settings': typeof DashboardDashboardExperimentsExperimentIdSettingsRoute
  '/_dashboard/dashboard/experiments/$experimentId/': typeof DashboardDashboardExperimentsExperimentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/experiments/$experimentId'
    | '/dashboard/experiments/'
    | '/dashboard/experiments/$experimentId/settings'
    | '/dashboard/experiments/$experimentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth'
    | '/dashboard'
    | '/dashboard/experiments'
    | '/dashboard/experiments/$experimentId/settings'
    | '/dashboard/experiments/$experimentId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/experiments/$experimentId'
    | '/_dashboard/dashboard/experiments/'
    | '/_dashboard/dashboard/experiments/$experimentId/settings'
    | '/_dashboard/dashboard/experiments/$experimentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/experiments/': {
      id: '/_dashboard/dashboard/experiments/'
      path: '/dashboard/experiments'
      fullPath: '/dashboard/experiments/'
      preLoaderRoute: typeof DashboardDashboardExperimentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId': {
      id: '/_dashboard/dashboard/experiments/$experimentId'
      path: '/dashboard/experiments/$experimentId'
      fullPath: '/dashboard/experiments/$experimentId'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId/': {
      id: '/_dashboard/dashboard/experiments/$experimentId/'
      path: '/'
      fullPath: '/dashboard/experiments/$experimentId/'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdIndexRouteImport
      parentRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId/settings': {
      id: '/_dashboard/dashboard/experiments/$experimentId/settings'
      path: '/settings'
      fullPath: '/dashboard/experiments/$experimentId/settings'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdSettingsRouteImport
      parentRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRoute
    }
  }
}

interface DashboardDashboardExperimentsExperimentIdRouteRouteChildren {
  DashboardDashboardExperimentsExperimentIdSettingsRoute: typeof DashboardDashboardExperimentsExperimentIdSettingsRoute
  DashboardDashboardExperimentsExperimentIdIndexRoute: typeof DashboardDashboardExperimentsExperimentIdIndexRoute
}

const DashboardDashboardExperimentsExperimentIdRouteRouteChildren: DashboardDashboardExperimentsExperimentIdRouteRouteChildren =
  {
    DashboardDashboardExperimentsExperimentIdSettingsRoute:
      DashboardDashboardExperimentsExperimentIdSettingsRoute,
    DashboardDashboardExperimentsExperimentIdIndexRoute:
      DashboardDashboardExperimentsExperimentIdIndexRoute,
  }

const DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren =
  DashboardDashboardExperimentsExperimentIdRouteRoute._addFileChildren(
    DashboardDashboardExperimentsExperimentIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardExperimentsExperimentIdRouteRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren
  DashboardDashboardExperimentsIndexRoute: typeof DashboardDashboardExperimentsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardExperimentsExperimentIdRouteRoute:
    DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren,
  DashboardDashboardExperimentsIndexRoute:
    DashboardDashboardExperimentsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
