/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardDashboardRouteRouteImport } from './routes/_dashboard/dashboard/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardDevicesIndexRouteImport } from './routes/_dashboard/dashboard/devices/index'
import { Route as DashboardDashboardExperimentsIndexRouteImport } from './routes/_dashboard/dashboard/experiments/index'
import { Route as DashboardDashboardExperimentsExperimentIdRouteRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/route'
import { Route as DashboardDashboardExperimentsNewRouteImport } from './routes/_dashboard/dashboard/experiments/new'
import { Route as DashboardDashboardExperimentsExperimentIdIndexRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/index'
import { Route as DashboardDashboardExperimentsExperimentIdCasesRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/cases'
import { Route as DashboardDashboardExperimentsExperimentIdSetupIndexRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/setup/index'
import { Route as DashboardDashboardExperimentsExperimentIdSetupInquiriesRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/setup/inquiries'
import { Route as DashboardDashboardExperimentsExperimentIdSetupInteractionRouteImport } from './routes/_dashboard/dashboard/experiments/$experimentId/setup/interaction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRouteRoute = DashboardDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRouteRoute,
} as any)
const DashboardDashboardDevicesIndexRoute =
  DashboardDashboardDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardExperimentsIndexRoute =
  DashboardDashboardExperimentsIndexRouteImport.update({
    id: '/experiments/',
    path: '/experiments/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdRouteRoute =
  DashboardDashboardExperimentsExperimentIdRouteRouteImport.update({
    id: '/experiments/$experimentId',
    path: '/experiments/$experimentId',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardExperimentsNewRoute =
  DashboardDashboardExperimentsNewRouteImport.update({
    id: '/experiments/new',
    path: '/experiments/new',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdIndexRoute =
  DashboardDashboardExperimentsExperimentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardExperimentsExperimentIdRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdCasesRoute =
  DashboardDashboardExperimentsExperimentIdCasesRouteImport.update({
    id: '/cases',
    path: '/cases',
    getParentRoute: () => DashboardDashboardExperimentsExperimentIdRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdSetupIndexRoute =
  DashboardDashboardExperimentsExperimentIdSetupIndexRouteImport.update({
    id: '/setup/',
    path: '/setup/',
    getParentRoute: () => DashboardDashboardExperimentsExperimentIdRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdSetupInquiriesRoute =
  DashboardDashboardExperimentsExperimentIdSetupInquiriesRouteImport.update({
    id: '/setup/inquiries',
    path: '/setup/inquiries',
    getParentRoute: () => DashboardDashboardExperimentsExperimentIdRouteRoute,
  } as any)
const DashboardDashboardExperimentsExperimentIdSetupInteractionRoute =
  DashboardDashboardExperimentsExperimentIdSetupInteractionRouteImport.update({
    id: '/setup/interaction',
    path: '/setup/interaction',
    getParentRoute: () => DashboardDashboardExperimentsExperimentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardDashboardRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/experiments/$experimentId': typeof DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren
  '/dashboard/experiments/new': typeof DashboardDashboardExperimentsNewRoute
  '/dashboard/devices/': typeof DashboardDashboardDevicesIndexRoute
  '/dashboard/experiments/': typeof DashboardDashboardExperimentsIndexRoute
  '/dashboard/experiments/$experimentId/cases': typeof DashboardDashboardExperimentsExperimentIdCasesRoute
  '/dashboard/experiments/$experimentId/': typeof DashboardDashboardExperimentsExperimentIdIndexRoute
  '/dashboard/experiments/$experimentId/setup/inquiries': typeof DashboardDashboardExperimentsExperimentIdSetupInquiriesRoute
  '/dashboard/experiments/$experimentId/setup/interaction': typeof DashboardDashboardExperimentsExperimentIdSetupInteractionRoute
  '/dashboard/experiments/$experimentId/setup/': typeof DashboardDashboardExperimentsExperimentIdSetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/experiments/new': typeof DashboardDashboardExperimentsNewRoute
  '/dashboard/devices': typeof DashboardDashboardDevicesIndexRoute
  '/dashboard/experiments': typeof DashboardDashboardExperimentsIndexRoute
  '/dashboard/experiments/$experimentId/cases': typeof DashboardDashboardExperimentsExperimentIdCasesRoute
  '/dashboard/experiments/$experimentId': typeof DashboardDashboardExperimentsExperimentIdIndexRoute
  '/dashboard/experiments/$experimentId/setup/inquiries': typeof DashboardDashboardExperimentsExperimentIdSetupInquiriesRoute
  '/dashboard/experiments/$experimentId/setup/interaction': typeof DashboardDashboardExperimentsExperimentIdSetupInteractionRoute
  '/dashboard/experiments/$experimentId/setup': typeof DashboardDashboardExperimentsExperimentIdSetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/experiments/$experimentId': typeof DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren
  '/_dashboard/dashboard/experiments/new': typeof DashboardDashboardExperimentsNewRoute
  '/_dashboard/dashboard/devices/': typeof DashboardDashboardDevicesIndexRoute
  '/_dashboard/dashboard/experiments/': typeof DashboardDashboardExperimentsIndexRoute
  '/_dashboard/dashboard/experiments/$experimentId/cases': typeof DashboardDashboardExperimentsExperimentIdCasesRoute
  '/_dashboard/dashboard/experiments/$experimentId/': typeof DashboardDashboardExperimentsExperimentIdIndexRoute
  '/_dashboard/dashboard/experiments/$experimentId/setup/inquiries': typeof DashboardDashboardExperimentsExperimentIdSetupInquiriesRoute
  '/_dashboard/dashboard/experiments/$experimentId/setup/interaction': typeof DashboardDashboardExperimentsExperimentIdSetupInteractionRoute
  '/_dashboard/dashboard/experiments/$experimentId/setup/': typeof DashboardDashboardExperimentsExperimentIdSetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/experiments/$experimentId'
    | '/dashboard/experiments/new'
    | '/dashboard/devices/'
    | '/dashboard/experiments/'
    | '/dashboard/experiments/$experimentId/cases'
    | '/dashboard/experiments/$experimentId/'
    | '/dashboard/experiments/$experimentId/setup/inquiries'
    | '/dashboard/experiments/$experimentId/setup/interaction'
    | '/dashboard/experiments/$experimentId/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth'
    | '/dashboard'
    | '/dashboard/experiments/new'
    | '/dashboard/devices'
    | '/dashboard/experiments'
    | '/dashboard/experiments/$experimentId/cases'
    | '/dashboard/experiments/$experimentId'
    | '/dashboard/experiments/$experimentId/setup/inquiries'
    | '/dashboard/experiments/$experimentId/setup/interaction'
    | '/dashboard/experiments/$experimentId/setup'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/experiments/$experimentId'
    | '/_dashboard/dashboard/experiments/new'
    | '/_dashboard/dashboard/devices/'
    | '/_dashboard/dashboard/experiments/'
    | '/_dashboard/dashboard/experiments/$experimentId/cases'
    | '/_dashboard/dashboard/experiments/$experimentId/'
    | '/_dashboard/dashboard/experiments/$experimentId/setup/inquiries'
    | '/_dashboard/dashboard/experiments/$experimentId/setup/interaction'
    | '/_dashboard/dashboard/experiments/$experimentId/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/devices/': {
      id: '/_dashboard/dashboard/devices/'
      path: '/devices'
      fullPath: '/dashboard/devices/'
      preLoaderRoute: typeof DashboardDashboardDevicesIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/experiments/': {
      id: '/_dashboard/dashboard/experiments/'
      path: '/experiments'
      fullPath: '/dashboard/experiments/'
      preLoaderRoute: typeof DashboardDashboardExperimentsIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId': {
      id: '/_dashboard/dashboard/experiments/$experimentId'
      path: '/experiments/$experimentId'
      fullPath: '/dashboard/experiments/$experimentId'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/experiments/new': {
      id: '/_dashboard/dashboard/experiments/new'
      path: '/experiments/new'
      fullPath: '/dashboard/experiments/new'
      preLoaderRoute: typeof DashboardDashboardExperimentsNewRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId/': {
      id: '/_dashboard/dashboard/experiments/$experimentId/'
      path: '/'
      fullPath: '/dashboard/experiments/$experimentId/'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdIndexRouteImport
      parentRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId/cases': {
      id: '/_dashboard/dashboard/experiments/$experimentId/cases'
      path: '/cases'
      fullPath: '/dashboard/experiments/$experimentId/cases'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdCasesRouteImport
      parentRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId/setup/': {
      id: '/_dashboard/dashboard/experiments/$experimentId/setup/'
      path: '/setup'
      fullPath: '/dashboard/experiments/$experimentId/setup/'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdSetupIndexRouteImport
      parentRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId/setup/inquiries': {
      id: '/_dashboard/dashboard/experiments/$experimentId/setup/inquiries'
      path: '/setup/inquiries'
      fullPath: '/dashboard/experiments/$experimentId/setup/inquiries'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdSetupInquiriesRouteImport
      parentRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRoute
    }
    '/_dashboard/dashboard/experiments/$experimentId/setup/interaction': {
      id: '/_dashboard/dashboard/experiments/$experimentId/setup/interaction'
      path: '/setup/interaction'
      fullPath: '/dashboard/experiments/$experimentId/setup/interaction'
      preLoaderRoute: typeof DashboardDashboardExperimentsExperimentIdSetupInteractionRouteImport
      parentRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRoute
    }
  }
}

interface DashboardDashboardExperimentsExperimentIdRouteRouteChildren {
  DashboardDashboardExperimentsExperimentIdCasesRoute: typeof DashboardDashboardExperimentsExperimentIdCasesRoute
  DashboardDashboardExperimentsExperimentIdIndexRoute: typeof DashboardDashboardExperimentsExperimentIdIndexRoute
  DashboardDashboardExperimentsExperimentIdSetupInquiriesRoute: typeof DashboardDashboardExperimentsExperimentIdSetupInquiriesRoute
  DashboardDashboardExperimentsExperimentIdSetupInteractionRoute: typeof DashboardDashboardExperimentsExperimentIdSetupInteractionRoute
  DashboardDashboardExperimentsExperimentIdSetupIndexRoute: typeof DashboardDashboardExperimentsExperimentIdSetupIndexRoute
}

const DashboardDashboardExperimentsExperimentIdRouteRouteChildren: DashboardDashboardExperimentsExperimentIdRouteRouteChildren =
  {
    DashboardDashboardExperimentsExperimentIdCasesRoute:
      DashboardDashboardExperimentsExperimentIdCasesRoute,
    DashboardDashboardExperimentsExperimentIdIndexRoute:
      DashboardDashboardExperimentsExperimentIdIndexRoute,
    DashboardDashboardExperimentsExperimentIdSetupInquiriesRoute:
      DashboardDashboardExperimentsExperimentIdSetupInquiriesRoute,
    DashboardDashboardExperimentsExperimentIdSetupInteractionRoute:
      DashboardDashboardExperimentsExperimentIdSetupInteractionRoute,
    DashboardDashboardExperimentsExperimentIdSetupIndexRoute:
      DashboardDashboardExperimentsExperimentIdSetupIndexRoute,
  }

const DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren =
  DashboardDashboardExperimentsExperimentIdRouteRoute._addFileChildren(
    DashboardDashboardExperimentsExperimentIdRouteRouteChildren,
  )

interface DashboardDashboardRouteRouteChildren {
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardExperimentsExperimentIdRouteRoute: typeof DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren
  DashboardDashboardExperimentsNewRoute: typeof DashboardDashboardExperimentsNewRoute
  DashboardDashboardDevicesIndexRoute: typeof DashboardDashboardDevicesIndexRoute
  DashboardDashboardExperimentsIndexRoute: typeof DashboardDashboardExperimentsIndexRoute
}

const DashboardDashboardRouteRouteChildren: DashboardDashboardRouteRouteChildren =
  {
    DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
    DashboardDashboardExperimentsExperimentIdRouteRoute:
      DashboardDashboardExperimentsExperimentIdRouteRouteWithChildren,
    DashboardDashboardExperimentsNewRoute:
      DashboardDashboardExperimentsNewRoute,
    DashboardDashboardDevicesIndexRoute: DashboardDashboardDevicesIndexRoute,
    DashboardDashboardExperimentsIndexRoute:
      DashboardDashboardExperimentsIndexRoute,
  }

const DashboardDashboardRouteRouteWithChildren =
  DashboardDashboardRouteRoute._addFileChildren(
    DashboardDashboardRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardDashboardRouteRoute: typeof DashboardDashboardRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardRouteRoute: DashboardDashboardRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
